using AdventOfCode;

//new AdventOfCode.Year2015.DayOne();
//new AdventOfCode.Year2015.DayTwo();
//new AdventOfCode.Year2015.DayThree();
//new AdventOfCode.Year2015.DayFour();
//new AdventOfCode.Year2015.DayFive();
//new AdventOfCode.Year2015.DaySix();
//new AdventOfCode.Year2015.DaySeven();
//new AdventOfCode.Year2015.DayEight();
//new AdventOfCode.Year2015.DayNine();
//new AdventOfCode.Year2015.DayTen();
//new AdventOfCode.Year2015.DayEleven();
//new AdventOfCode.Year2015.DayTwelve();

//new AdventOfCode.Year2016.DayOne();

//new AdventOfCode.Year2017.DayOne();

//new AdventOfCode.Year2018.DayOne();
//new AdventOfCode.Year2018.DayTwentyThree();

//new AdventOfCode.Year2019.DayOne();
//new AdventOfCode.Year2019.DayTwo();

//new AdventOfCode.Year2020.DayOne();
//new AdventOfCode.Year2020.DayTwo();
//new AdventOfCode.Year2020.DayThree();
//new AdventOfCode.Year2020.DayFour();
//new AdventOfCode.Year2020.DayFive();
//new AdventOfCode.Year2020.DaySix();
//new AdventOfCode.Year2020.DaySeven();
//new AdventOfCode.Year2020.DayEight();
//new AdventOfCode.Year2020.DayNine();
//new AdventOfCode.Year2020.DayTen();
//new AdventOfCode.Year2020.DayEleven();
//new AdventOfCode.Year2020.DayTwelve();
//new AdventOfCode.Year2020.DayThirteen();
//new AdventOfCode.Year2020.DayFourteen();
//new AdventOfCode.Year2020.DayFifteen();
//new AdventOfCode.Year2020.DaySixteen();
//new AdventOfCode.Year2020.DaySeventeen();
//new AdventOfCode.Year2020.DayEighteen();
//new AdventOfCode.Year2020.DayNineteen();
//new AdventOfCode.Year2020.DayTwenty();
//new AdventOfCode.Year2020.DayTwentyOne();
//new AdventOfCode.Year2020.DayTwentyTwo();
//new AdventOfCode.Year2020.DayTwentyThree();
//new AdventOfCode.Year2020.DayTwentyFour();
//new AdventOfCode.Year2020.DayTwentyFive();

//new AdventOfCode.Year2021.DayOne();
//new AdventOfCode.Year2021.DayTwo();
//new AdventOfCode.Year2021.DayThree();
//new AdventOfCode.Year2021.DayFour();
//new AdventOfCode.Year2021.DayFive();
//new AdventOfCode.Year2021.DaySix();
//new AdventOfCode.Year2021.DaySeven();
//new AdventOfCode.Year2021.DayEight();
//new AdventOfCode.Year2021.DayNine();
//new AdventOfCode.Year2021.DayTen();
//new AdventOfCode.Year2021.DayEleven();
//new AdventOfCode.Year2021.DayTwelve();
//new AdventOfCode.Year2021.DayThirteen();
//new AdventOfCode.Year2021.DayFourteen();
//new AdventOfCode.Year2021.DayFifteen();
//new AdventOfCode.Year2021.DaySixteen();
//new AdventOfCode.Year2021.DaySeventeen();
//new AdventOfCode.Year2021.DayEighteen();
//new AdventOfCode.Year2021.DayNineteen();
//new AdventOfCode.Year2021.DayTwenty();
//new AdventOfCode.Year2021.DayTwentyOne();
//new AdventOfCode.Year2021.DayTwentyTwo();
//new AdventOfCode.Year2021.DayTwentyThree();
//new AdventOfCode.Year2021.DayTwentyFour();
//new AdventOfCode.Year2021.DayTwentyFive();

//new AdventOfCode.Year2022.DayOne();
//new AdventOfCode.Year2022.DayTwo();
//new AdventOfCode.Year2022.DayThree();
//new AdventOfCode.Year2022.DayFour();
//new AdventOfCode.Year2022.DayFive();
//new AdventOfCode.Year2022.DaySix();
//new AdventOfCode.Year2022.DaySeven();
//new AdventOfCode.Year2022.DayEight();
//new AdventOfCode.Year2022.DayNine();
//new AdventOfCode.Year2022.DayTen();
//new AdventOfCode.Year2022.DayEleven();
//new AdventOfCode.Year2022.DayTwelve();
//new AdventOfCode.Year2022.DayThirteen();
//new AdventOfCode.Year2022.DayFourteen();
//new AdventOfCode.Year2022.DayFifteen();
//new AdventOfCode.Year2022.DaySixteen();
//new AdventOfCode.Year2022.DaySeventeen();
//new AdventOfCode.Year2022.DayEighteen();
//new AdventOfCode.Year2022.DayNineteen();
//new AdventOfCode.Year2022.DayTwenty();
//new AdventOfCode.Year2022.DayTwentyOne();
//new AdventOfCode.Year2022.DayTwentyTwo();
//new AdventOfCode.Year2022.DayTwentyThree();
//new AdventOfCode.Year2022.DayTwentyFour();
//new AdventOfCode.Year2022.DayTwentyFive();

//new AdventOfCode.Year2023.DayOne();
//new AdventOfCode.Year2023.DayTwo();
//new AdventOfCode.Year2023.DayThree();
//new AdventOfCode.Year2023.DayFour();
//new AdventOfCode.Year2023.DayFive();
//new AdventOfCode.Year2023.DaySix();
//new AdventOfCode.Year2023.DaySeven();
//new AdventOfCode.Year2023.DayEight();
//new AdventOfCode.Year2023.DayNine();
//new AdventOfCode.Year2023.DayTen();
//new AdventOfCode.Year2023.DayEleven();
//new AdventOfCode.Year2023.DayTwelve();
//new AdventOfCode.Year2023.DayThirteen();
//new AdventOfCode.Year2023.DayFourteen();
//new AdventOfCode.Year2023.DayFifteen();
//new AdventOfCode.Year2023.DaySixteen();
//new AdventOfCode.Year2023.DaySeventeen();
//new AdventOfCode.Year2023.DayEighteen();
//new AdventOfCode.Year2023.DayNineteen();
//new AdventOfCode.Year2023.DayTwenty();
//new AdventOfCode.Year2023.DayTwentyOne();
//new AdventOfCode.Year2023.DayTwentyTwo();
//new AdventOfCode.Year2023.DayTwentyThree();
//new AdventOfCode.Year2023.DayTwentyFour();

//new AdventOfCode.Year2024.DayOne();
//new AdventOfCode.Year2024.DayTwo();
//new AdventOfCode.Year2024.DayThree();
//new AdventOfCode.Year2024.DayFour();
//new AdventOfCode.Year2024.DayFive();
//new AdventOfCode.Year2024.DaySix();
//new AdventOfCode.Year2024.DaySeven();
//new AdventOfCode.Year2024.DayEight();
//new AdventOfCode.Year2024.DayNine();
//new AdventOfCode.Year2024.DayTen();
//new AdventOfCode.Year2024.DayEleven();
//new AdventOfCode.Year2024.DayTwelve();
//new AdventOfCode.Year2024.DayThirteen();
new AdventOfCode.Year2024.DayFourteen();

//Day2015.CalculateAndLogResults();
//Console.WriteLine();
//Day2016.CalculateAndLogResults();
//Console.WriteLine();
//Day2017.CalculateAndLogResults();
//Console.WriteLine();
//Day2018.CalculateAndLogResults();
//Console.WriteLine();
//Day2019.CalculateAndLogResults();
//Console.WriteLine();
//Day2020.CalculateAndLogResults();
//Console.WriteLine();
//Day2021.CalculateAndLogResults();
//Console.WriteLine();
//Day2022.CalculateAndLogResults();
//Console.WriteLine();
//Day2023.CalculateAndLogResults();
//Console.WriteLine();
Day2024.CalculateAndLogResults();